---
name: "Build & Test MacPorts Base"

on:
  - push
  - pull_request

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11, ubuntu-20.04]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 64
      - name: Cleanup /usr/local
        run: |
          sudo mkdir /opt/local.old
          sudo mv /usr/local/* /opt/local.old
      - name: Install Linux Dependencies
        if: startsWith(matrix.os,'ubuntu')
        run: >
          sudo apt update &&
          sudo apt install mtree-netbsd
          gnustep libcurl4-gnutls-dev libmd-dev
      - name: Configure MacPorts Base
        run: |
          set -eu
          ./configure
      - name: Build MacPorts Base
        run: |
          set -eu
          platform=$(uname -s)
          case ${platform} in
            Darwin) make -j$(sysctl -n hw.activecpu)
            ;;
            Linux) make -j$(nproc)
            ;;
          esac
      - name: Install MacPorts Base
        run: |
          set -eu
          sudo make install
      - name: Test MacPorts Base
        run: |
          set -eu
          make test
